const els = {
  logout: document.getElementById('logoutBtn'), name: document.getElementById('profileName'), email: document.getElementById('profileEmail'), org: document.getElementById('profileOrg'), areas: document.getElementById('profileAreas'), emailNotifications: document.getElementById('emailNotifications'), save: document.getElementById('saveProfileBtn'), msg: document.getElementById('profileMessage'), matchMsg: document.getElementById('matchMessage'), list: document.getElementById('matchedPublications')
};
let currentUser = null;
let currentProfile = null;
function parseAreas(value){ return [...new Set(String(value||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean))]; }
function show(target, message, isError=false){ target.textContent=message; target.classList.remove('hidden'); target.style.background=isError?'#fff1f1':'#edf7f1'; target.style.color=isError?'#9b1c1c':'#0d4d2e'; }
function renderPubs(items){ els.list.innerHTML=''; if(!items?.length){ els.list.innerHTML='<p class="muted">No matching publications yet. Update your research areas or check back later.</p>'; return; } items.forEach(pub=>{ const row=document.createElement('article'); row.className='admin-row'; row.innerHTML=`<img src="${pub.cover_url || 'assets/placeholder-cover.svg'}" alt="${pub.title} cover"><div><strong>${pub.title}</strong><p class="muted">${pub.type || 'Publication'} • ${pub.year || 'N/A'}${pub.authors ? ' • ' + pub.authors : ''}</p><p class="muted">Research areas: ${(pub.research_areas || []).join(', ') || 'Not set'}</p></div><a class="btn btn-secondary" href="viewer.html?id=${encodeURIComponent(pub.id)}">Read</a>`; els.list.appendChild(row); }); }
async function loadDashboard(){ if(!window.db){ show(els.matchMsg,'Update js/config.js with your Supabase credentials.',true); return; } const {data:{session}} = await window.db.auth.getSession(); if(!session?.user){ window.location.href='login.html'; return; } currentUser=session.user; const {data:profile,error:pErr}=await window.db.from('profiles').select('*').eq('id', currentUser.id).maybeSingle(); if(pErr){ show(els.matchMsg,pErr.message,true); return; } currentProfile=profile || { id: currentUser.id, email: currentUser.email, research_areas: [] }; els.name.textContent=currentProfile.full_name || currentUser.email; els.email.textContent=currentProfile.email || currentUser.email; els.org.textContent=currentProfile.organisation || 'No organisation set'; els.areas.value=(currentProfile.research_areas || []).join(', '); els.emailNotifications.checked = currentProfile.email_notifications !== false; await loadMatches(); }
async function loadMatches(){ const areas=parseAreas(els.areas.value); let query=window.db.from('publications_with_stats').select('*').order('created_at',{ascending:false}); if(areas.length) query=query.overlaps('research_areas', areas); const {data,error}=await query; if(error){ show(els.matchMsg,error.message,true); return; } renderPubs(data || []); }
els.save?.addEventListener('click', async()=>{ const research_areas=parseAreas(els.areas.value); show(els.msg,'Saving preferences...'); const payload={ id: currentUser.id, full_name: currentProfile?.full_name || currentUser.email, email: currentUser.email, organisation: currentProfile?.organisation || null, research_areas, email_notifications: els.emailNotifications.checked, role: currentProfile?.role || 'viewer' }; const {error}=await window.db.from('profiles').upsert(payload); if(error) return show(els.msg,error.message,true); show(els.msg,'Preferences saved.'); currentProfile={...currentProfile,...payload}; await loadMatches(); });
els.logout?.addEventListener('click', async()=>{ await window.db.auth.signOut(); window.location.href='login.html'; });
loadDashboard();
