(function(){
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
function toast(msg){let t=$('#drToast');if(!t){t=document.createElement('div');t.id='drToast';t.className='dr-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.__drToast);window.__drToast=setTimeout(()=>t.classList.remove('show'),2400)}
function modal(title,kicker,body){let b=$('#drModalBackdrop');if(!b){b=document.createElement('div');b.id='drModalBackdrop';b.className='dr-modal-backdrop';b.innerHTML='<div class="dr-modal"><div class="dr-modal-head"><div><strong id="drModalTitle"></strong><div class="dr-modal-kicker" id="drModalKicker"></div></div><button class="dr-close" id="drClose">×</button></div><div class="dr-modal-body" id="drModalBody"></div><div class="dr-modal-actions" id="drModalActions"></div></div>';document.body.appendChild(b);b.addEventListener('click',e=>{if(e.target===b||e.target.id==='drClose')close()})}$('#drModalTitle').textContent=title;$('#drModalKicker').textContent=kicker;$('#drModalBody').innerHTML=body;$('#drModalActions').innerHTML='<button class="dr-action-btn" id="drCancel">Close</button><button class="dr-action-btn primary" id="drConfirm">Confirm</button>';$('#drCancel').onclick=close;$('#drConfirm').onclick=()=>{close();toast('Action recorded in the RMRDC Deal Room.')};b.classList.add('open')}
function close(){$('#drModalBackdrop')?.classList.remove('open')}
function tab(name){$$('.dr-tab').forEach(x=>x.classList.remove('active'));$$('.dr-tab-content').forEach(x=>x.classList.remove('active'));const b=$(`.dr-tab[data-tab="${name}"]`);const c=$(`#tab-${name}`);b?.classList.add('active');c?.classList.add('active');if(history.replaceState)history.replaceState(null,'','#'+name)}
function openDeal(btn){const card=btn.closest('.dr-deal');const name=card?.querySelector('h3')?.textContent||'RMRDC Technology Opportunity';const stage=card?.querySelector('.stage')?.textContent||'Active engagement';modal(name,'Controlled opportunity workspace',`<div class="dr-modal-grid"><div class="dr-modal-card"><small>OPPORTUNITY</small><h3>${name}</h3><p>Review the approved opportunity record, stakeholder activity and next commercialisation action.</p></div><div class="dr-modal-card"><small>CURRENT STAGE</small><h3>${stage}</h3><p>RMRDC controls sensitive information, access and stage transitions.</p></div></div>`)}
function genericButton(btn){const txt=btn.textContent.trim().toLowerCase();if(txt.includes('open deal'))return openDeal(btn);if(txt.includes('data room')||txt.includes('documents')||txt.includes('ip documents')||txt.includes('technical brief')||txt.includes('technical drawings')){tab('documents');toast('Controlled data room opened.');return}if(txt.includes('message')){tab('messages');toast('Opportunity messages opened.');return}if(txt.includes('meeting')||txt.includes('fabricator match')){tab('meetings');toast('Meetings and engagement opened.');return}if(txt==='open'||txt.includes('action')){tab('tasks');toast('Your actions opened.');return}modal(btn.textContent.trim(),'RMRDC controlled workflow','<div class="dr-modal-card"><small>WORKSPACE ACTION</small><h3>'+btn.textContent.trim()+'</h3><p>This action is routed through the RMRDC controlled Deal Room workflow. You can review, respond or request access before the stage advances.</p></div>')}
document.addEventListener('DOMContentLoaded',()=>{
$$('.dr-tab').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
$$('.dr-actions button,.dr-task button,.dr-meeting button').forEach(b=>b.addEventListener('click',()=>genericButton(b)));
$$('.dr-deal-title h3').forEach(h=>h.style.cursor='pointer');$$('.dr-deal-title h3').forEach(h=>h.addEventListener('click',()=>openDeal(h)));
const filter=$('.dr-filter');if(filter){let stages=['All stages','Investor Interest','Due Diligence','Engineering Match','Scale-up'];let idx=0;filter.addEventListener('click',()=>{idx=(idx+1)%stages.length;filter.textContent=stages[idx]+' ▾';const v=stages[idx].toLowerCase();let shown=0;$$('.dr-deal').forEach(c=>{const text=c.innerText.toLowerCase();const ok=idx===0||text.includes(v.replace('investor interest','interest').replace('engineering match','engineering'));c.style.display=ok?'':'none';if(ok)shown++});toast(shown+' opportunity'+(shown===1?'':'ies')+' shown')})}
const hash=location.hash.replace('#','');if(['pipeline','tasks','documents','messages','meetings'].includes(hash))tab(hash);
});
})();
