const form=document.getElementById('subscriptionForm'),message=document.getElementById('subscriptionMessage'),savedProfileBox=document.getElementById('savedProfileBox'),loginForm=document.getElementById('subscriberLoginForm'),loginMessage=document.getElementById('loginMessage');
const PROFILE_KEY='rmrdc_cas_profile',LOGIN_KEY='rmrdc_subscriber_logged_in';
function splitList(t=''){return String(t).split(',').map(v=>v.trim()).filter(Boolean)}
function checked(){return Array.from(document.querySelectorAll('.interest-grid input:checked')).map(i=>i.value)}
function notice(el,text,err=false){if(!el)return;el.textContent=text;el.classList.remove('hidden');el.style.background=err?'#fff1f1':'#edf7f1';el.style.color=err?'#9b1c1c':'#0d4d2e'}
function renderProfile(){const p=JSON.parse(localStorage.getItem(PROFILE_KEY)||'null');savedProfileBox.innerHTML=p?`<div class="profile-summary"><strong>${p.full_name}</strong><p>${p.email}</p><p>${p.organisation||''}</p><div class="interest-tags">${p.research_areas.map(a=>`<span>${a}</span>`).join('')}</div></div>`:'<p class="muted">No subscription profile saved yet.</p>'}
async function saveOnline(p){if(!window.db)return;const{error}=await window.db.from('research_subscribers').upsert({full_name:p.full_name,email:p.email,organisation:p.organisation,phone:p.phone,research_areas:p.research_areas.map(v=>v.toLowerCase()),email_notifications:p.email_notifications,whatsapp_alerts:p.whatsapp_alerts},{onConflict:'email'});if(error)throw error}
form?.addEventListener('submit',async e=>{e.preventDefault();const interests=[...new Set([...checked(),...splitList(document.getElementById('customInterests').value)])];if(!interests.length)return notice(message,'Please select at least one research interest.',true);const p={full_name:document.getElementById('subName').value.trim(),email:document.getElementById('subEmail').value.trim().toLowerCase(),organisation:document.getElementById('subOrganisation').value.trim(),phone:document.getElementById('subPhone').value.trim(),research_areas:interests,email_notifications:document.getElementById('subEmailAlerts').checked,whatsapp_alerts:document.getElementById('subWhatsappAlerts').checked,saved_at:new Date().toISOString()};try{localStorage.setItem(PROFILE_KEY,JSON.stringify(p));localStorage.setItem(LOGIN_KEY,JSON.stringify({email:p.email,logged_at:new Date().toISOString()}));await saveOnline(p);notice(message,'Subscription saved. You are now logged in and can open your dashboard.');renderProfile();setTimeout(()=>location.href='user-dashboard.html',900)}catch(err){console.error(err);notice(message,'Saved locally, but Supabase save failed. You can still open your dashboard on this device.',true);renderProfile()}})
loginForm?.addEventListener('submit',async e=>{e.preventDefault();const email=document.getElementById('loginEmail').value.trim().toLowerCase();let found=null;if(window.db){const{data,error}=await window.db.from('research_subscribers').select('*').eq('email',email).maybeSingle();if(!error&&data)found={full_name:data.full_name,email:data.email,organisation:data.organisation,phone:data.phone,research_areas:data.research_areas||[],email_notifications:data.email_notifications,whatsapp_alerts:data.whatsapp_alerts}}const local=JSON.parse(localStorage.getItem(PROFILE_KEY)||'null');if(!found&&local?.email===email)found=local;if(!found)return notice(loginMessage,'No subscription found for this email. Please subscribe first.',true);localStorage.setItem(PROFILE_KEY,JSON.stringify(found));localStorage.setItem(LOGIN_KEY,JSON.stringify({email,logged_at:new Date().toISOString()}));notice(loginMessage,'Login successful. Opening your dashboard...');setTimeout(()=>location.href='user-dashboard.html',700)})
document.querySelectorAll('.auth-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.auth-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.getElementById('registerPanel').classList.toggle('hidden',btn.dataset.authTab!=='register');document.getElementById('loginPanel').classList.toggle('hidden',btn.dataset.authTab!=='login')}));renderProfile();