import { createClient } from "npm:@supabase/supabase-js@2";

const allowedOrigins=(Deno.env.get("CORS_ALLOWED_ORIGINS")||"http://localhost:5501,http://127.0.0.1:5501").split(',').map(x=>x.trim()).filter(Boolean);
function headers(req:Request){const origin=req.headers.get('origin')||'';return {"Access-Control-Allow-Origin":allowedOrigins.includes(origin)?origin:allowedOrigins[0],"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-internal-processing-secret","Content-Type":"application/json"}}
const json=(req:Request,body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:headers(req)});
async function digest(response:Response,maxBytes:number){const chunks:Uint8Array[]=[];let total=0;for await(const chunk of response.body||[]){total+=chunk.byteLength;if(total>maxBytes)throw new Error('Document exceeds configured download limit');chunks.push(chunk)}const bytes=new Uint8Array(total);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}const hash=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,'0')).join('')}
Deno.serve(async req=>{
  if(req.method==='OPTIONS')return new Response('ok',{headers:headers(req)});
  const token=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!token)return json(req,{error:'Authentication required'},401);
  const url=Deno.env.get('SUPABASE_URL')!,serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const userDb=createClient(url,Deno.env.get('SUPABASE_ANON_KEY')||serviceKey,{global:{headers:{Authorization:`Bearer ${token}`}}});const {data:{user}}=await userDb.auth.getUser(token);if(!user)return json(req,{error:'Authentication required'},401);const {data:isStaff}=await userDb.rpc('is_platform_staff');if(!isStaff)return json(req,{error:'Staff authorization required'},403);
  const admin=createClient(url,serviceKey);const {data:documents,error}=await admin.from('technology_documents').select('id,storage_bucket,storage_path,source_hash,status').order('updated_at',{ascending:true});if(error)return json(req,{error:error.message},500);
  const internalSecret=Deno.env.get('DOCUMENT_PROCESSING_INTERNAL_SECRET');if(!internalSecret)return json(req,{error:'DOCUMENT_PROCESSING_INTERNAL_SECRET is not configured'},503);const maxBytes=Number(Deno.env.get('PADDLEOCR_MAX_DOWNLOAD_BYTES')||104857600);const results=[];
  for(const document of documents||[]){try{const active=await admin.from('document_processing_jobs').select('id').eq('document_id',document.id).in('status',['queued','processing']).limit(1);if(active.data?.length){results.push({document_id:document.id,status:'already_processing'});continue}const signed=await admin.storage.from(document.storage_bucket).createSignedUrl(document.storage_path,600);if(signed.error||!signed.data?.signedUrl){await admin.from('technology_documents').update({status:'missing',last_error:'Storage object is missing or unavailable',updated_at:new Date().toISOString()}).eq('id',document.id);results.push({document_id:document.id,status:'missing'});continue}const source=await fetch(signed.data.signedUrl,{redirect:'error'});if(source.status===404||source.status===410){await admin.from('technology_documents').update({status:'missing',last_error:`Storage object returned HTTP ${source.status}`,updated_at:new Date().toISOString()}).eq('id',document.id);results.push({document_id:document.id,status:'missing'});continue}if(!source.ok)throw new Error(`Storage download failed (${source.status})`);const sourceHash=await digest(source,maxBytes);if(document.status==='completed'&&document.source_hash===sourceHash){results.push({document_id:document.id,status:'skipped',reason:'unchanged'});continue}const nextStatus=document.status==='completed'?'completed':'queued';await admin.from('technology_documents').update({source_hash:sourceHash,status:nextStatus,last_error:null,updated_at:new Date().toISOString()}).eq('id',document.id);const jobUrl=`${url}/functions/v1/process-technology-document`;const processed=await fetch(jobUrl,{method:'POST',headers:{Authorization:`Bearer ${serviceKey}`,'Content-Type':'application/json','X-Internal-Processing-Secret':internalSecret},body:JSON.stringify({document_id:document.id})});results.push({document_id:document.id,status:processed.ok?'processed':'failed'});}catch(error){const message=error instanceof Error?error.message:'Sync failed';await admin.from('technology_documents').update({status:'failed',last_error:message}).eq('id',document.id);results.push({document_id:document.id,status:'failed',error:message})}}
  return json(req,{documents:results});
});
